apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nugrohop2003/backend:1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
          - name: BASE_URL_PORT
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: BASE_URL_PORT
                env: 
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret 
                key: DATABASE_USERNAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DATABASE_PASSWORD
          - name: DATABASE_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DATABASE_DATABASE
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: mysecret 
                key: DATABASE_HOST
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: DATABASE_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: service-backend
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: be-ingress
  labels:
    name: be-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: backend.zonadesain.id
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: service-backend
            port: 
              number: 5000
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  labels: 
    app: backend
type: Opaque
data:
  BASE_URL_PORT: "5000"
  DATABASE_USERNAME: YWRtaW4=
  DATABASE_PASSWORD: MTIzNDU2Nzg=
  DATABASE_DATABASE: cGVvcGxl
  DATABASE_HOST: database-cilist.c5obzm6tolho.ap-southeast-1.rds.amazonaws.com
  DATABASE_PORT: "3306"




